app_dir=/media/sd/roms/ports/3sx/app
save_dir=/media/sd/saves/ports/3sx
log_dir=/media/sd/roms/ports/3sx/logs
iso_path=/media/sd/roms/ports/3sx/3sx.iso
resource_path=/media/sd/roms/ports/3sx/SF33RD.AFS
scale_mode=square-pixels
crt_native_mode=true
crt_mode_width=320
crt_mode_height=240
crt_mode_refresh=auto
sdl_videodriver=kmsdrm
sdl_audiodriver=alsa
sdl_kmsdrm_device_index=1
timing_240p60="320 1 20 32 45 240 1 2 3 16 0 0 0 60.000000 0 6514560 1"
timing_240p50=
